### ISSUE TITLE
RuntimeError: Failed to load audio: [WinError 2]

### ISSUE THREAD

**Issue by pixol20** [JarodMica/tts-pipeline-example#2]
When using pyttsx3 example this error appears
Here's a log
```2023-09-24 12:03:34 | INFO | comtypes.client._code_cache | Imported existing <module 'comtypes.gen' from 'M:\\AIAssistant\\venv\\lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-09-24 12:03:34 | INFO | comtypes.client._code_cache | Using writeable comtypes cache directory: 'M:\AIAssistant\venv\lib\site-packages\comtypes\gen'
Available voices:
0: Microsoft Irina Desktop - Russian
1: Microsoft Zira Desktop - English (United States)
audio file path: output/out.wav
loading pth Vega.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "m:\aiassistant\venv\src\rvc\lib\audio.py", line 14, in load_audio
    ffmpeg.input(file, threads=0)
  File "M:\AIAssistant\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "M:\AIAssistant\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "M:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "M:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\AIAssistant\main.py", line 51, in <module>
    rvc_convert(model_path="Vega.pth",
  File "m:\aiassistant\venv\src\rvc-tts-pipe\rvc_infer.py", line 337, in rvc_convert
    wav_opt=vc_single(0,input_path,f0_up_key,None,f0method,file_index,file_index2,index_rate,filter_radius,resample_sr,rms_mix_rate,protect)
  File "m:\aiassistant\venv\src\rvc-tts-pipe\rvc_infer.py", line 159, in vc_single
    audio = load_audio(input_audio_path, 16000)
  File "m:\aiassistant\venv\src\rvc\lib\audio.py", line 19, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] Не удается найти указанный файл

Process finished with exit code 1
```

**Comment by pixol20** [comment]
Fixed issue by replacing code in audio.py file. audio.py is located in venv/src/rvc/lib. Also you will need to install av using this command `pip install av`
Here is this code 
```
import librosa
import numpy as np
import av
from io import BytesIO


def wav2(i, o, format):
    inp = av.open(i, "rb")
    if format == "m4a":
        format = "mp4"
    out = av.open(o, "wb", format=format)
    if format == "ogg":
        format = "libvorbis"
    if format == "mp4":
        format = "aac"

    ostream = out.add_stream(format)

    for frame in inp.decode(audio=0):
        for p in ostream.encode(frame):
            out.mux(p)

    for p in ostream.encode(None):
        out.mux(p)

    out.close()
    inp.close()


def audio2(i, o, format, sr):
    inp = av.open(i, "rb")
    out = av.open(o, "wb", format=format)
    if format == "ogg":
        format = "libvorbis"
    if format == "f32le":
        format = "pcm_f32le"

    ostream = out.add_stream(format, channels=1)
    ostream.sample_rate = sr

    for frame in inp.decode(audio=0):
        for p in ostream.encode(frame):
            out.mux(p)

    out.close()
    inp.close()


def load_audio(file, sr):
    try:
        file = (
            file.strip(" ").strip('"').strip("\n").strip('"').strip(" ")
        )  # 防止小白拷路径头尾带了空格和"和回车
        with open(file, "rb") as f:
            with BytesIO() as out:
                audio2(f, out, "f32le", sr)
                return np.frombuffer(out.getvalue(), np.float32).flatten()

    except AttributeError:
        audio = file[1] / 32768.0
        if len(audio.shape) == 2:
            audio = np.mean(audio, -1)
        return librosa.resample(audio, orig_sr=file[0], target_sr=16000)

    except Exception as e:
        raise RuntimeError(f"Failed to load audio: {e}")
        
```

**Comment by QuickLike** [comment]
> Fixed issue by replacing code in audio.py file. audio.py is located in venv/src/rvc/lib. Also you will need to install av using this command `pip install av` Here is this code
> 
> ```
> import librosa
> import numpy as np
> import av
> from io import BytesIO
> 
> 
> def wav2(i, o, format):
>     inp = av.open(i, "rb")
>     if format == "m4a":
>         format = "mp4"
>     out = av.open(o, "wb", format=format)
>     if format == "ogg":
>         format = "libvorbis"
>     if format == "mp4":
>         format = "aac"
> 
>     ostream = out.add_stream(format)
> 
>     for frame in inp.decode(audio=0):
>         for p in ostream.encode(frame):
>             out.mux(p)
> 
>     for p in ostream.encode(None):
>         out.mux(p)
> 
>     out.close()
>     inp.close()
> 
> 
> def audio2(i, o, format, sr):
>     inp = av.open(i, "rb")
>     out = av.open(o, "wb", format=format)
>     if format == "ogg":
>         format = "libvorbis"
>     if format == "f32le":
>         format = "pcm_f32le"
> 
>     ostream = out.add_stream(format, channels=1)
>     ostream.sample_rate = sr
> 
>     for frame in inp.decode(audio=0):
>         for p in ostream.encode(frame):
>             out.mux(p)
> 
>     out.close()
>     inp.close()
> 
> 
> def load_audio(file, sr):
>     try:
>         file = (
>             file.strip(" ").strip('"').strip("\n").strip('"').strip(" ")
>         )  # 防止小白拷路径头尾带了空格和"和回车
>         with open(file, "rb") as f:
>             with BytesIO() as out:
>                 audio2(f, out, "f32le", sr)
>                 return np.frombuffer(out.getvalue(), np.float32).flatten()
> 
>     except AttributeError:
>         audio = file[1] / 32768.0
>         if len(audio.shape) == 2:
>             audio = np.mean(audio, -1)
>         return librosa.resample(audio, orig_sr=file[0], target_sr=16000)
> 
>     except Exception as e:
>         raise RuntimeError(f"Failed to load audio: {e}")
>         
> ```

Thank you so much, buddy! I've been fiddling with this error all damn day. It finally worked!

**Comment by Chipsfisch** [comment]
Important to note:
You have to use an older version of av to get this version of the audio.py ffile to work.
https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/1915#issuecomment-2073585668
